### ISSUE TITLE
unable to click buttons from bot  messages

### ISSUE THREAD

**Issue by pcking999** [Brightscout/mattermost-plugin-exchange-calendar#46]
when I type

/mscalendar settings 

the bot messages me to adjust my settings. However I am unable to click any of the button and unable to change any settings. for example for the question

Do you want to update your status on Mattermost when you are in a meeting?
Current value: No

i am given yes and no buttons but when i click either button nothing happens. This is on both the desktop app and the web based app. when i look at developers tools in chrome i get the following when i click the buttons

client4.js:2037     POST https://mattermost.domain.com/api/v4/posts/6mitdnobnpgj3b8bkgspbf1t3c/actions/gsc1qkbattdamboz5mjqkasg9e 400

this is on mattermost omnibus 8.0.1 and Release v2.3.2 of the plugin.

**Comment by mkdbns** [comment]
@pcking999 , our dev team is looking into this issue and will report back here once it is diagnosed. Sorry for the delay.

**Comment by Kshitij-Katiyar** [comment]
@pcking999 Can you please check whether the site url in the mattermost config setting and the url you are accessing the mattermost is same or not because some times this error comes when they are different.

**Comment by pcking999** [comment]
the urls are the same.

**Comment by pcking999** [comment]
We have nginx proxy in front of the mattermost server that accepts TLS connections to the mattermost server and redirects the user to https. The base url was configured for http. after updating that url the plugin worked.
